const mongoose = require('mongoose');

// กำหนด Schema
const computerSchema = new mongoose.Schema({
    BrandCom: String,
    ModelCom: String,
    BrandCPU: String,
    SeriesCPU: String,
    ModelCPU: String,
    CPU_Base_Clock: Number,
    PriceCPU: Number,
    BrandMainboard: String,
    ModelMainboard: String,
    Mainboard_CPU_Support: String,
    MemoryMainboard: Number,
    Mainboard_Memory_Support: String,
    PriceMainboard: Number,
    BrandVGA: String,
    ChipsetVGA: String,
    SeriesVGA: String,
    ModelVGA: String,
    VGA_Base_Clock: Number,
    VGA_Boost_Clock: Number,
    VGA_Memory_Clock: Number,
    VGA_Memory_Size: Number,
    PriceVGA: Number,
    RAM_Size: Number,
    RAM_Speed: Number,
    PriceRAM: Number,
    CapacitySSD: Number,
    Read_SSD: Number,
    Write_SSD: Number,
    PriceSSD: Number,
    CapacitySSD2: Number,
    Read_SSD2: Number,
    Write_SSD2: Number,
    PriceSSD2: Number,
    CapacityHDD: Number,
    Speed_HDD: Number,
    PriceHDD: Number,
    PS: Number,
    PricePS: Number,
    BrandCASE: String,
    ModelCASE: String,
    WeightCASE: Number,
    I_O_Ports_CASE: String,
    PriceCASE: Number,
    BrandCOOLING: String,
    ModelCOOLING: String,
    Fan_Built_In_COOLING: String,
    PriceCOOLING: Number,
    BrandMONITOR: String,
    ModelMONITOR: String,
    Display_Size_MONITOR: Number,
    Max_Resolution_MONITOR: String,
    Refresh_Rate_MONITOR: Number,
    PriceMONITOR: Number,
    Rank1: String,
    Rank2: String,
    Rank3: String,
    ProbabilityRank1: Number,
    ProbabilityRank2: Number,
    ProbabilityRank3: Number
  });

  
// สร้างโมเดลจาก Schema
const Spec = mongoose.model('spec_coms', computerSchema);

module.exports = { Spec };